// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://peqxpmhamdciyqtdkoqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcXhwbWhhbWRjaXlxdGRrb3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDU2NjksImV4cCI6MjA3MzY4MTY2OX0.w_O3tHYd8nYueeg2IiQMYFS7RHt28toqLuowEXPbG3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});